rpm: build.h File Reference
build.h File Reference
Functions
int build (rpmts ts, const char *arg, BTA_t ba, const char *rcfile)
Function Documentation
int build (rpmts ts, const char * arg, BTA_t ba, const char * rcfile)
Definition at line 279 of file build.c.
References _, _RPMVSF_NODIGESTS, _RPMVSF_NOSIGNATURES, rpmBuildArguments_s::buildAmount, buildCleanMask, buildForTarget(), rpmBuildArguments_s::qva_flags, rpmExpandNumeric(), rpmFreeMacros(), rpmFreeRpmrc(), rpmReadConfigFiles(), rpmtsSetVSFlags(), RPMVSF_NOHDRCHK, rpmBuildArguments_s::targets, VERIFY_DIGEST, VERIFY_HDRCHK, VERIFY_SIGNATURE, and xmalloc().
Referenced by main().